import {createRequire} from 'node:module';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const dir='/Users/kevin/PROJECTS/vampire-survivors-2026/artifacts/post-campfire-performance';
await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=metal','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const report={revision:'Saved production candidate with campfire lighting fix',method:'Exact Git revision, production build, local solo host, Chromium/Metal, 1100x740 CSS pixels, sequential feature ablation; elapsed RAF frames include simulation and rendering. Feature changes take effect only around world draw and are restored afterward.',errors:[],samples:[]};
try {
 const page=await browser.newPage({viewport:{width:1100,height:740},deviceScaleFactor:2});page.setDefaultTimeout(120000);
 page.on('pageerror',e=>report.errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('killsync.friends.menu.pause','true');localStorage.setItem('sunline.preferences.v1',JSON.stringify({renderScale:1,shadows:true}));window.auditFrames=[];let last;function tick(t){if(last)window.auditFrames.push({at:t,ms:t-last});last=t;requestAnimationFrame(tick);}requestAnimationFrame(tick);});
 await page.route('**/assets/FriendsMenuScene-*.js',r=>r.fulfill({contentType:'application/javascript',body:'export function createFriendsMenuScene(){return()=>{};}'}));
 await page.goto('http://127.0.0.1:3032/?mode=friends',{waitUntil:'domcontentloaded'});
 await page.getByLabel('Your name',{exact:true}).fill('Deployment audit');await page.getByRole('button',{name:'Play on my own',exact:true}).click({noWaitAfter:true});await page.locator('.coop-arena').waitFor({state:'attached'});
 await page.evaluate(()=>{const el=document.querySelector('.coop-arena');let fiber=el[Object.keys(el).find(k=>k.startsWith('__reactFiber'))],sim,bridge;while(fiber){let h=fiber.memoizedState;while(h){const v=h.memoizedState?.current;if(v?.createSnapshot&&v?.setInput)sim=v;if(v?.getFriendsTerrain&&v?.setFriendsTool)bridge=v;h=h.next;}fiber=fiber.return;}if(!sim||!bridge)throw Error('Missing arena refs');bridge.setFriendsEnvironment({hour:12,speed:0});window.audit={sim,bridge,mode:'baseline',draws:[],times:[],counts:new Map()};const r=bridge.renderer.renderer,scene=bridge.renderer.scene,old=r.render.bind(r);r.render=function(s,c){if(s!==scene)return old(s,c);const changes=[];s.traverse(o=>{let hide=(audit.mode==='no-forest'&&o.name==='frontier-instanced-3d-forests')||(audit.mode==='no-clouds'&&o.name==='frontier-volumetric-cumulus')||((audit.mode==='no-fire'||audit.mode==='no-fire-geometry')&&o.name==='commons-campfire-gathering')||(audit.mode==='no-birds'&&o.name==='friends-birds')||(audit.mode==='no-distant-blocks'&&(o.name==='frontier-persistent-block-horizon'||o.name==='frontier-block-surface-shells'))||(audit.mode==='no-volumes'&&[...bridge.frontierVisuals.chunks.values()].includes(o));if(hide){changes.push([o,o.visible]);o.visible=false;}if(audit.mode==='no-shadows'&&o.isLight&&o.castShadow){changes.push([o,'shadow']);o.castShadow=false;}});let savedIntensity;const fire=s.getObjectByName('commons-campfire-light');if(audit.mode==='no-fire'||audit.mode==='no-fire-light'){savedIntensity=fire.intensity;fire.intensity=0;}const start=performance.now();try{return old(s,c);}finally{if(savedIntensity!==undefined)fire.intensity=savedIntensity;audit.times.push(performance.now()-start);audit.draws.push({calls:r.info.render.calls,triangles:r.info.render.triangles});for(const [o,v]of changes){if(v==='shadow')o.castShadow=true;else o.visible=v;}}};});
 await page.waitForFunction(()=>!audit.bridge.friendsWorldArrival.sequence.active,{timeout:120000});await page.waitForTimeout(10000);
 report.startup=await page.evaluate(()=>({largestFrameMs:Math.max(...auditFrames.map(f=>f.ms)),over100ms:auditFrames.filter(f=>f.ms>100).length,warmup:audit.bridge.renderer.friendsShaderWarmup?.stats,preparation:audit.bridge.friendsWorldArrival.preparationStats}));
 async function sample(label,mode,scale=1){
   await page.evaluate(({mode,scale})=>{audit.mode=mode;audit.bridge.setLocalPreferences({renderScale:scale,shadows:true,lookSensitivity:1});},{mode,scale});await page.waitForTimeout(3000);
   const start=await page.evaluate(()=>{audit.draws=[];audit.times=[];return performance.now();});await page.waitForTimeout(8000);
   const result=await page.evaluate(({label,start})=>{const q=xs=>{const s=xs.slice().sort((a,b)=>a-b);return {n:s.length,mean:s.reduce((a,b)=>a+b,0)/s.length,p50:s[Math.floor(s.length*.5)],p95:s[Math.floor(s.length*.95)],max:s.at(-1)};};const a=audit,b=a.bridge,r=b.renderer.renderer,gl=r.getContext(),forest=b.frontierVisuals.forestStats,lights=[],objects=[];b.renderer.scene.traverse(o=>{if(o.isLight)lights.push({name:o.name,type:o.type,visible:o.visible,intensity:o.intensity,shadow:o.castShadow});if(o.isMesh&&o.visible&&o.name.startsWith('forest-'))objects.push({name:o.name,count:o.count,triangles:o.count*(o.geometry.index?.count||o.geometry.attributes.position.count)/3});});const debug=gl.getExtension('WEBGL_debug_renderer_info');return {label,mode:a.mode,buffer:[r.domElement.width,r.domElement.height],frameMs:q(auditFrames.filter(f=>f.at>start).map(f=>f.ms)),worldSubmitMs:q(a.times),drawCalls:q(a.draws.map(d=>d.calls)),triangles:q(a.draws.map(d=>d.triangles)),forest,forestBuckets:objects,lights,gpu:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),stats:b.getPerformanceStats(),glError:gl.getError()};},{label,start});report.samples.push(result);console.log(JSON.stringify({label,frame:result.frameMs,submit:result.worldSubmitMs,draws:result.drawCalls.mean,tris:result.triangles.mean,forest:result.forest}));
 }

 await page.evaluate(()=>{const p=[...audit.sim.players.values()][0];Object.assign(p,{x:6470,y:5552,z:704,verticalVelocity:0});audit.bridge.renderer.yaw=-Math.PI/2;audit.bridge.renderer.pitch=-.1;});await page.waitForTimeout(20000);
 for(const [label,mode,scale] of [['fixed campfire baseline','baseline',1],['forest hidden','no-forest',1],['distant terrain shells hidden','no-distant-blocks',1],['near voxel terrain hidden','no-volumes',1],['clouds hidden','no-clouds',1],['render scale .7','baseline',.7],['render scale .5','baseline',.5],['full resolution baseline repeat','baseline',1]])await sample(label,mode,scale);
 const cdp=await page.context().newCDPSession(page);await cdp.send('Profiler.enable');await cdp.send('Profiler.start');await page.waitForTimeout(5000);const {profile}=await cdp.send('Profiler.stop');await writeFile(dir+'/camp.cpuprofile',JSON.stringify(profile));const weights=new Map();profile.samples.forEach((id,i)=>weights.set(id,(weights.get(id)||0)+(profile.timeDeltas[i]||0)));report.cpu=profile.nodes.map(n=>({name:n.callFrame.functionName,line:n.callFrame.lineNumber+1,url:n.callFrame.url,ms:(weights.get(n.id)||0)/1000})).sort((a,b)=>b.ms-a.ms).slice(0,30);report.details=await page.evaluate(()=>({position:audit.bridge.renderer.camera.position,nightvision:audit.bridge.renderer.nightVision.blend,lights:audit.bridge.renderer.renderer.info.programs.map(p=>({id:p.id,point:p.cacheKey.match(/NUM_POINT_LIGHTS/g)?.length,ready:p.isReady()}))}));await page.screenshot({path:dir+'/baseline.png'});
}catch(e){report.failure=String(e);throw e;}finally{await writeFile(dir+'/ablation.json',JSON.stringify(report,null,2));await browser.close();}
