import { PLAYER_TRAIN_COST } from '../game/world/FriendsPlayerRail';
import { FRIENDS_TOOL_ORDER } from '../game/multiplayer/FriendsToolControls';
import { useState } from 'react';
import { Axe, Pickaxe, Shovel, Sprout, Crosshair, X, Package, TrainFront, Hammer, Compass, ArrowRight, Cable } from 'lucide-react';
import { FRONTIER_TOOLS, MATERIAL_NAMES, PACK_CAPACITY, emptyMaterials, packKey, packWeight, canAfford, frontierContract, type FrontierSnapshot, type FrontierRequest, type FrontierTool, type Resource } from '../game/multiplayer/FriendsFrontier';
import type { CoopPlayerSnapshot } from '../game/multiplayer/CoopSimulation';
import { FRONTIER_SITES } from '../game/world/FriendsTerrain';
const icons = [Crosshair, Axe, Pickaxe, Shovel, Sprout, Cable];
const formatCost = (cost: Partial<Record<Resource, number>>) => Object.entries(cost).map(([r, n]) => `${n} ${MATERIAL_NAMES[r as Resource].toLowerCase()}`).join(' · ');
export function FriendsToolbelt({ frontier, player, tool, onTool, onPack, elapsed, visible=true }: { frontier: FrontierSnapshot; player: CoopPlayerSnapshot; tool: FrontierTool; onTool: (tool: FrontierTool) => void; onPack: () => void; elapsed: number; visible?:boolean }) {
  const pack = frontier.packs[packKey(player)] || emptyMaterials(), feedback = frontier.feedback[player.id];
  return <>
    {feedback && feedback.until > elapsed && <div className="frontier-feedback" role="status">{feedback.message}</div>}
    {frontier.damage && (frontier.damage.until || 0) > elapsed && <div className="frontier-harvest-progress"><span>{frontier.damage.value >= frontier.damage.total ? 'HARVESTED' : tool === 1 ? 'CUTTING' : 'EXCAVATING'}</span><progress value={frontier.damage.value} max={frontier.damage.total} /><small>{frontier.damage.value}/{frontier.damage.total}</small></div>}
    <section className="frontier-toolbelt" data-visible={visible} aria-hidden={!visible} inert={!visible} aria-label="Frontier tools" onMouseDown={e => e.stopPropagation()} onPointerDown={e => e.stopPropagation()}>
      <div className="frontier-toolbelt__stock"><span><Package size={13} /> {packWeight(pack)}/{frontier.testing ? '∞' : PACK_CAPACITY}</span><span>{pack.wood} timber</span><span>{pack.stone} stone</span><span>{pack.copper + pack.iron} ore</span></div>
      <div className="frontier-toolbelt__slots">{FRIENDS_TOOL_ORDER.map((id, i) => { const Icon = icons[id]; return <button key={id} type="button" aria-pressed={tool === id} onClick={() => onTool(id)} title={id === 4 ? 'Place harvested soil' : FRONTIER_TOOLS[id]}><kbd>{i + 1}</kbd><Icon size={23} /><span>{FRONTIER_TOOLS[id]}</span></button>; })}<button type="button" onClick={onPack}><kbd>G</kbd><Package size={23} /><span>Field pack</span></button></div>
      <small>{tool === 5 ? 'Click attach / release · hold aim to reel · crouch + aim feeds rope · R release · F secure / unload' : `${frontier.testing ? 'FREE BUILDING · UNLIMITED PACK · ' : ''}Hold click to ${tool === 1 ? 'cut a tree trunk' : tool === 2 ? 'mine stone and ore' : tool === 3 ? 'excavate earth' : tool === 4 ? 'place soil' : 'fire'} · B build · M atlas`}</small>
    </section>
  </>;
}
export function FriendsFieldPack({ frontier, player, tool, onTool, onRequest, onClose, message }: { frontier: FrontierSnapshot; player: CoopPlayerSnapshot; tool: FrontierTool; onTool: (tool: FrontierTool) => void; onRequest: (request: Omit<FrontierRequest, 'requestId'>) => void; onClose: () => void; message: string | null }) {
  const [tab, setTab] = useState('Pack');
  const pack = frontier.packs[packKey(player)] || emptyMaterials();
  const goals = [
    { done: frontier.chopped > 0, title: 'Bring down your first cedar', detail: 'Equip the axe, walk up to a trunk and hold the primary action.' },
    { done: frontier.mined > 0, title: 'Break into the earth', detail: 'The Lantern Descent starts northeast of arrival. Follow the torchlit rim down into the underground chambers. Copper Hollow is southeast.' },
    { done: frontier.built > 0, title: 'Make the frontier yours', detail: frontier.testing ? 'B opens construction. All pieces are free during testing.' : 'B opens construction. Your field pack pays for each piece.' },
    { done: frontier.upgrades > 0, title: 'Forge reinforced tools', detail: 'Smelt ore and cut planks at a workshop. Upgrade the tools for your entire crew.' },
  ];
  const order = frontierContract(frontier.contracts), contract = order.cost;
  const recipe = (action: FrontierRequest['action'], name: string, cost: Partial<Record<Resource, number>>, detail: string) => <button className="frontier-recipe" type="button" key={action} disabled={!(frontier.testing && action==='train_place' || canAfford(pack, cost) || canAfford(frontier.stock, cost)) || action === 'upgrade' && frontier.upgrades > 0} onClick={() => onRequest({ action })}><div><Hammer size={20} /><strong>{name}</strong><ArrowRight size={16} /></div><p>{detail}</p><small>{frontier.testing && action==='train_place' ? 'Free during testing' : formatCost(cost)}</small></button>;
  return <div className="frontier-pack-backdrop" onMouseDown={e => e.stopPropagation()} onPointerDown={e => e.stopPropagation()}>
    <section className="frontier-pack" role="dialog" aria-modal="true" aria-label="Frontier field pack">
      <header><span><small>SUNLINE / FIELD NOTES</small><h2>Your next great expedition.</h2><p>Gather. Make. Connect. Come back to what you built.</p></span><button type="button" onClick={onClose} aria-label="Close field pack"><X size={22} /></button></header>
      <nav aria-label="Field pack sections">{['Pack', 'Workshop', 'Grand Traverse', 'Rail cargo', 'Journal'].map(t => <button key={t} type="button" aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
      <div className="frontier-pack__body">
        {tab === 'Pack' && <><div className="frontier-pack__heading"><Package size={20} /><h3>Carry something worth building with.</h3><span>{packWeight(pack)}/{frontier.testing ? '∞' : PACK_CAPACITY}</span></div><div className="frontier-materials">{(Object.keys(MATERIAL_NAMES) as Resource[]).map(r => <div key={r}><span>{MATERIAL_NAMES[r]}</span><strong>{pack[r]}</strong><small>{frontier.stock[r]} in shared storage</small><button type="button" disabled={!frontier.stock[r]} onClick={() => onRequest({ action: 'withdraw', resource: r })}>Withdraw up to 24</button></div>)}</div><div className="frontier-pack__actions"><button onClick={() => onRequest({ action: 'deposit' })}><Package size={17} />Deposit pack at a workshop</button><button onClick={() => onRequest({ action: 'plant' })} disabled={!pack.saplings}><Sprout size={17} />Plant a cedar</button></div><p className="frontier-pack__hint">Materials stay in your pack until you deposit them. Storage is shared by the crew. Your field pack and train cargo have no carry limit during testing.</p></>}
        {tab === 'Workshop' && <><div className="frontier-pack__heading"><Hammer size={20} /><h3>A little ore. A bigger possibility.</h3></div><p className="frontier-pack__hint">Build your own field workbench, furnace or storage chest before crafting. Recipes use your pack first, then shared storage.</p><div className="frontier-recipes">{recipe('planks', 'Cut 4 planks', { wood: 2 }, 'Timber becomes supply chests and better tools.')}{recipe('smelt_copper', 'Smelt copper', { copper: 2, wood: 1 }, 'Produce 1 ingot for metal construction.')}{recipe('smelt_iron', 'Smelt iron', { iron: 2, wood: 1 }, 'Produce 2 ingots from deeper seams.')}{recipe('upgrade', frontier.upgrades ? 'Reinforced tools unlocked' : 'Reinforce crew tools', { ingots: 4, planks: 8 }, 'Faster cutting and mining for everyone in this world.')}</div></>}
        {tab === 'Grand Traverse' && <><div className="frontier-pack__heading"><TrainFront size={20}/><h3>A whole island from your seat.</h3></div><p className="frontier-pack__hint">Walk south of arrival to the level platform at Sunline Commons. The sightseeing train visits Highfall Meadow, Tidal Shore, Ember Meadow and Skyfalls Shore. Board an open carriage and F to sit. F or jump stands up; look around freely throughout the ride. The atlas shows the complete route. The service stops automatically at every station.</p><div className="frontier-pack__actions"><button onClick={()=>onRequest({action:'scenic_hold'})}>Hold sightseeing train</button><button onClick={()=>onRequest({action:'scenic_depart'})}>Resume sightseeing tour</button></div><p className="frontier-pack__hint">Controls require building access and proximity to the train. Existing construction stays saved; the service holds if it obstructs the line.</p></>}
        {tab === 'Rail cargo' && <><div className="frontier-pack__heading"><TrainFront size={20} /><h3>The railway has a purpose.</h3><span>{packWeight(frontier.cargo)}/{frontier.testing ? '∞' : 2000}</span></div><p className="frontier-pack__hint">B → Railway builds straight and curved tracks. Connect matching ends on level ground or a bridge. Stand beside your track to assemble a train; longer lines add up to three open carriages. Open lines shuttle between their ends; closed loops run continuously. Board or stand beside a carriage to transfer cargo. Cargo and supplies persist when the host saves.</p><div className="frontier-materials">{(Object.keys(MATERIAL_NAMES) as Resource[]).filter(r => frontier.cargo[r] > 0).map(r => <div key={r}><span>{MATERIAL_NAMES[r]}</span><strong>{frontier.cargo[r]}</strong><small>On the Sunline train</small></div>)}</div>{packWeight(frontier.cargo) === 0 && <div className="frontier-empty"><TrainFront size={38} /><p>Your first shipment starts with a harvest.</p></div>}<div className="frontier-recipes">{recipe('train_place', 'Assemble train on my track', PLAYER_TRAIN_COST, 'Stand within reach of your track. The train starts held; depart when you are ready.')}</div><div className="frontier-pack__actions"><button onClick={() => onRequest({ action: 'train_remove' })}>Dismantle held train</button><button onClick={() => onRequest({ action: 'load' })}>Load field pack onto train</button><button onClick={() => onRequest({ action: 'train_hold' })}>Hold train for loading</button><button onClick={() => onRequest({ action: 'train_depart' })}>Depart now</button><button onClick={() => onRequest({ action: 'unload' })}>Collect cargo into field pack</button></div></>}
        {tab === 'Journal' && <><div className="frontier-pack__heading"><Compass size={20} /><h3>A frontier, a crew, a thousand plans.</h3></div><div className="frontier-goals">{goals.map(g => <div key={g.title} data-done={g.done}><span>{g.done ? '✓' : '○'}</span><section><strong>{g.title}</strong><p>{g.detail}</p></section></div>)}</div><div className="frontier-contract"><small>SUPPLY ORDER {String(frontier.contracts + 1).padStart(2, '0')}</small><h3>Keep the frontier moving.</h3><p>{order.destination ? `Carry ${formatCost(contract)} to ${order.destination.name}. Land beside the survey flag and deliver from here.` : `Deliver ${formatCost(contract)} to your shared storage.`}</p><span>Reward: {order.reward} ingots + 2 saplings · {frontier.contracts} orders delivered</span><button disabled={!canAfford(order.destination ? pack : frontier.stock, contract)} onClick={() => onRequest({ action: 'contract' })}>Deliver supplies</button></div><div className="frontier-destinations">{FRONTIER_SITES.map(site => <p key={site.id}><strong>{frontier.discovered?.includes(site.id) ? '✓ ' : '○ '}{site.name}</strong><span>{Math.round(Math.hypot(player.x - site.x, player.y - site.y) / 12)}m · {site.detail}</span></p>)}</div></>}
      </div>
      <footer><span role="status">{message || 'The host saves your terrain, supplies, cargo and settlement.'}</span><button onClick={() => onRequest({ action: 'home' })}>Return to arrival point</button></footer>
    </section>
  </div>;
}
