export const GAME_WIDTH = 4000;
export const GAME_HEIGHT = 4000;

export const INITIAL_PLAYER_STATS = {
  might: 1,
  area: 1,
  speed: 1,
  cooldown: 1,
  amount: 0,
  luck: 1,
  growth: 1,
  greed: 1,
  regen: 0,
  magnet_range: 1,
  dash_cooldown: 1,
  boss_damage: 1,
  extra_weapon: 0,
  overdrive_duration: 0,
  vampirism: 0,
  armor: 0,
  timeWarp: 0,
};

export const WEAPON_DEFINITIONS = [
  {
    id: 'plasma_gun',
    name: 'Plasma Gun',
    description: 'Automatically fires at the nearest enemy. Upgrades add burst fire.',
    type: 'projectile',
    baseCooldown: 1200,
    baseDamage: 12,
    baseSize: 12,
    evolution: 'supernova_cannon',
    burstCount: 1,
    burstDelay: 200
  },
  {
    id: 'orbit_drones',
    name: 'Orbit Drones',
    description: 'Drones that circle the player, damaging anything they touch.',
    type: 'orbit',
    baseCooldown: 0,
    baseDamage: 8,
    baseSize: 18,
    evolution: 'satellite_array'
  },
  {
    id: 'neon_shards',
    name: 'Neon Shards',
    description: 'Fires shards at the nearest enemy.',
    type: 'projectile',
    baseCooldown: 1200,
    baseDamage: 18,
    baseSize: 12,
    evolution: 'prism_burst'
  },
  {
    id: 'void_aura',
    name: 'Void Aura',
    description: 'Damages enemies in a radius around the player.',
    type: 'area',
    baseCooldown: 500,
    baseDamage: 12,
    baseSize: 120,
    evolution: 'black_hole'
  },
  {
    id: 'neural_pulse',
    name: 'Neural Pulse',
    description: 'A circular shockwave that expands from the player.',
    type: 'area',
    baseCooldown: 3000,
    baseDamage: 40,
    baseSize: 150,
    evolution: 'synapse_burst'
  },
  {
    id: 'data_scythe',
    name: 'Data Scythe',
    description: 'A rotating beam that orbits the player.',
    type: 'orbit',
    baseCooldown: 0,
    baseDamage: 6,
    baseSize: 20,
    evolution: 'reaper_protocol'
  },
  {
    id: 'cyber_blade',
    name: 'Cyber Blade',
    description: 'A close-range swipe that damages enemies in front of the player.',
    type: 'projectile',
    baseCooldown: 700,
    baseDamage: 45,
    baseSize: 100,
    evolution: 'monomolecular_edge'
  },
  {
    id: 'sonic_boom',
    name: 'Sonic Boom',
    description: 'Fires a high-frequency wave that pushes enemies back.',
    type: 'projectile',
    baseCooldown: 2000,
    baseDamage: 20,
    baseSize: 80,
    evolution: 'supersonic_pulse'
  },
  {
    id: 'nano_swarm',
    name: 'Nano Swarm',
    description: 'Releases a swarm of nanites that seek out enemies.',
    type: 'projectile',
    baseCooldown: 2000,
    baseDamage: 25,
    baseSize: 10,
    evolution: 'grey_goo'
  },
  {
    id: 'phantom_chain',
    name: 'Phantom Chain',
    description: 'Chain lightning that bounces between up to 6 enemies, arcing with electric fury.',
    type: 'projectile',
    baseCooldown: 3000,
    baseDamage: 25,
    baseSize: 8,
    evolution: 'storm_nexus'
  },
  {
    id: 'gravity_well',
    name: 'Gravity Well',
    description: 'Deploys a miniature black hole that sucks in and crushes nearby enemies.',
    type: 'area',
    baseCooldown: 6000,
    baseDamage: 15,
    baseSize: 200,
    evolution: 'singularity'
  },
  {
    id: 'mirror_shards',
    name: 'Mirror Shards',
    description: 'Fires prismatic shards that ricochet off invisible walls, leaving rainbow trails.',
    type: 'projectile',
    baseCooldown: 1800,
    baseDamage: 14,
    baseSize: 10,
    evolution: 'kaleidoscope'
  },
  {
    id: 'spectral_helix',
    name: 'Spectral Helix',
    description: 'Fires a double-helix DNA spiral of energy that corkscrews through enemies.',
    type: 'projectile',
    baseCooldown: 2200,
    baseDamage: 25,
    baseSize: 15,
    evolution: 'genome_breaker'
  },
  {
    id: 'void_tendrils',
    name: 'Void Tendrils',
    description: 'Dark tendrils reach from the void beneath you, lashing at the 3 nearest enemies.',
    type: 'area',
    baseCooldown: 3500,
    baseDamage: 45,
    baseSize: 300,
    evolution: 'eldritch_grasp'
  },
  {
    id: 'solar_flare',
    name: 'Solar Flare',
    description: 'Unleashes a blazing cone of plasma in your facing direction.',
    type: 'area',
    baseCooldown: 2800,
    baseDamage: 24,
    baseSize: 250,
    evolution: 'supernova'
  },
  {
    id: 'quantum_echo',
    name: 'Quantum Echo',
    description: 'Spawns ghost afterimages that replay your path and deal damage on contact.',
    type: 'area',
    baseCooldown: 4000,
    baseDamage: 30,
    baseSize: 20,
    evolution: 'parallel_self'
  },
  {
    id: 'frost_aura',
    name: 'Frost Aura',
    description: 'Emits a soft, chilling pulse that damages and slows enemies.',
    type: 'area',
    baseCooldown: 4000,
    baseDamage: 25,
    baseSize: 200,
    evolution: 'absolute_zero'
  },
  {
    id: 'stardust',
    name: 'Stardust',
    description: 'Gentle, glowing stars fall from above, striking enemies with cosmic light.',
    type: 'projectile',
    baseCooldown: 10000,
    baseDamage: 100,
    baseSize: 15,
    evolution: 'meteor_shower'
  },
  {
    id: 'arc_weaver',
    name: 'Arc Weaver',
    description: 'Spins an electric web between nearby enemies, zapping everything caught inside.',
    type: 'area',
    baseCooldown: 3000,
    baseDamage: 20,
    baseSize: 350,
    evolution: 'neural_net'
  }
];

export const UPGRADES = [
  { id: 'might', name: 'Neural Might', description: 'Increases damage by 15%', type: 'stat', icon: 'zap', rarity: 'common' },
  { id: 'area', name: 'Expansion Protocol', description: 'Increases attack size by 15%', type: 'stat', icon: 'target', rarity: 'common' },
  { id: 'speed', name: 'Overclocked Servos', description: 'Increases movement speed by 10%', type: 'stat', icon: 'activity', rarity: 'common' },
  { id: 'cooldown', name: 'Rapid Cycle', description: 'Reduces cooldown by 10%', type: 'stat', icon: 'clock', rarity: 'common' },
  { id: 'growth', name: 'Data Siphon', description: 'Increases XP gain by 20%', type: 'stat', icon: 'trending-up', rarity: 'common' },
  { id: 'amount', name: 'Duplication Glitch', description: 'Adds +1 projectile to all weapons', type: 'stat', icon: 'copy', rarity: 'rare' },
  { id: 'health', name: 'Core Integrity', description: 'Increases max health by 25%', type: 'stat', icon: 'heart', rarity: 'common' },
  { id: 'luck', name: 'Probability Hack', description: 'Increases luck by 15%', type: 'stat', icon: 'dice', rarity: 'common' },
  { id: 'regen', name: 'Auto-Repair', description: 'Regenerates 2 HP every 5 seconds', type: 'stat', icon: 'plus-circle', rarity: 'rare' },
  { id: 'vampirism', name: 'Data Vampirism', description: 'Killing enemies restores 3 HP', type: 'stat', icon: 'droplet', rarity: 'rare' },
  { id: 'double_strike', name: 'Double Strike', description: 'All attacks have 20% chance to hit twice', type: 'stat', icon: 'repeat', rarity: 'rare' },
  { id: 'armor', name: 'Adaptive Plating', description: 'Reduces incoming damage by 25%', type: 'stat', icon: 'shield', rarity: 'rare' },
  { id: 'god_mode', name: 'God Mode', description: 'Massive boost to all stats for 30s', type: 'stat', icon: 'shield', rarity: 'legendary' },
  { id: 'instant_kill', name: 'Executioner', description: 'Small chance to instant kill non-bosses', type: 'stat', icon: 'skull', rarity: 'legendary' },
  { id: 'chain_lightning', name: 'Chain Resonance', description: 'Kills have 15% chance to damage 5 nearby enemies', type: 'stat', icon: 'zap', rarity: 'legendary' },
  { id: 'time_warp', name: 'Time Dilation', description: 'Enemies move 20% slower permanently', type: 'stat', icon: 'clock', rarity: 'legendary' },
  { id: 'gold_rush', name: 'Gold Rush Protocol', description: 'Triple gold drops for 60 seconds', type: 'stat', icon: 'dollar-sign', rarity: 'rare' },
  { id: 'magnet_range', name: 'Signal Amplifier', description: 'Increases pickup range by 25%', type: 'stat', icon: 'wifi', rarity: 'common' }
];

export const DASH_UPGRADES = [
  { id: 'dash_deadlock_burst', name: 'Deadlock Burst', description: 'Dash: Standing still 1s charges a massive shockwave on your next dash.', rarity: 'common' },
  { id: 'dash_twin_vector', name: 'Twin Vector', description: 'Dash: Gain a second dash charge that refills independently.', rarity: 'rare' },
  { id: 'dash_aegis_slip', name: 'Aegis Slip', description: 'Dash: Become shielded during dash and 0.35s after, blocking all damage.', rarity: 'rare' },
  { id: 'dash_afterimage_minefield', name: 'Afterimage Minefield', description: 'Dash: Leave 3 afterimages that detonate after 0.5s dealing AoE damage.', rarity: 'legendary' },
  { id: 'dash_phase_laceration', name: 'Phase Laceration', description: 'Dash: Enemies crossed during dash take heavy slice damage.', rarity: 'legendary' },
  { id: 'dash_null_wake', name: 'Null Wake', description: 'Dash: Leave a slowing trail for 1.2s that cripples enemy movement.', rarity: 'common' },
  { id: 'dash_inertia_vault', name: 'Inertia Vault', description: 'Dash: Dash distance and speed scale with your current move speed.', rarity: 'rare' },
  { id: 'dash_kinetic_refund', name: 'Kinetic Refund', description: 'Dash: Kills within 1.5s after dashing refund 15% dash cooldown each.', rarity: 'rare' },
  { id: 'dash_bulwark_ram', name: 'Bulwark Ram', description: 'Dash: First enemy hit is knocked back hard, stunned, and takes 3x damage.', rarity: 'common' },
  { id: 'dash_echo_recall', name: 'Echo Recall', description: 'Dash: Re-press dash within 0.7s to blink back to your start point.', rarity: 'legendary' },
  { id: 'dash_prism_guard', name: 'Prism Guard', description: 'Dash: Gain 4 rotating shards for 2s that damage nearby enemies.', rarity: 'legendary' },
  { id: 'dash_cataclysm_brake', name: 'Cataclysm Brake', description: 'Dash: Stopping after dash creates an implosion pulling enemies inward.', rarity: 'legendary' },
];

export const ITEM_TYPES = {
  hp: { color: '#ff3366', value: 30, weight: 0.4, shape: 'heart' },
  coin_bronze: { color: '#cd7f32', value: 2, weight: 0.4, shape: 'circle' },
  coin_silver: { color: '#c0c0c0', value: 10, weight: 0.2, shape: 'circle' },
  coin_gold: { color: '#ffd700', value: 20, weight: 0.05, shape: 'circle' },
  coin_diamond: { color: '#b9f2ff', value: 100, weight: 0.01, shape: 'circle' },
  magnet: { color: '#00ccff', value: 1, weight: 0.1, shape: 'magnet' },
  bomb: { color: '#ff8800', value: 100, weight: 0.1, shape: 'bomb' },
  data_core: { color: '#ffffff', value: 1, weight: 0.0, shape: 'star' } // Zero weight: manually spawned by elite/boss
};

export const ENEMY_TYPES = {
  basic: {
    health: 12,
    speed: 1.0,
    damage: 10,
    radius: 15,
    xp: 5,
    color: '#ff4444',
    name: 'Drone',
    visual: 'circle'
  },
  fast: {
    health: 50,
    speed: 1.4,
    damage: 12,
    radius: 14,
    xp: 12,
    color: '#ffaa00',
    name: 'Scout',
    visual: 'triangle'
  },
  tank: {
    health: 180,
    speed: 0.9,
    damage: 30,
    radius: 25,
    xp: 30,
    color: '#8800ff',
    name: 'Goliath',
    visual: 'square'
  },
  ranged: {
    health: 60,
    speed: 1.3,
    damage: 18,
    radius: 18,
    xp: 20,
    color: '#00ff88',
    name: 'Sniper',
    visual: 'diamond'
  },
  elite: {
    health: 500,
    speed: 1.2,
    damage: 45,
    radius: 35,
    xp: 100,
    color: '#ff00ff',
    name: 'Elite Guard',
    visual: 'hexagon'
  },
  phantom: {
    health: 80,
    speed: 2.2,
    damage: 15,
    radius: 20,
    xp: 50,
    color: '#ffffff',
    name: 'Phantom',
    visual: 'ghost'
  },
  titan: {
    health: 1200,
    speed: 0.6,
    damage: 55,
    radius: 60,
    xp: 500,
    color: '#ff0000',
    name: 'Titan',
    visual: 'star'
  }
};

export const PERMANENT_UPGRADES = [
  { id: 'perm_might', name: 'Neural Overdrive', description: 'Permanent +10% Damage', baseCost: 500, costScale: 1.5, maxLevel: 5, stat: 'might', value: 0.1 },
  { id: 'perm_area', name: 'Void Expansion', description: 'Permanent +10% Area', baseCost: 500, costScale: 1.5, maxLevel: 5, stat: 'area', value: 0.1 },
  { id: 'perm_speed', name: 'Kinetic Boost', description: 'Permanent +5% Move Speed', baseCost: 400, costScale: 1.4, maxLevel: 5, stat: 'speed', value: 0.05 },
  { id: 'perm_cooldown', name: 'Clock Sync', description: 'Permanent -3% Cooldown', baseCost: 600, costScale: 1.6, maxLevel: 5, stat: 'cooldown', value: -0.03 },
  { id: 'perm_growth', name: 'XP Optimizer', description: 'Permanent +10% XP Gain', baseCost: 300, costScale: 1.3, maxLevel: 5, stat: 'growth', value: 0.1 },
  { id: 'perm_greed', name: 'Gold Magnet', description: 'Permanent +10% Gold Gain', baseCost: 300, costScale: 1.3, maxLevel: 5, stat: 'greed', value: 0.1 },
  { id: 'perm_luck', name: 'Fortune Hack', description: 'Permanent +10% Luck', baseCost: 400, costScale: 1.4, maxLevel: 5, stat: 'luck', value: 0.1 },
  { id: 'perm_health', name: 'Hull Reinforcement', description: 'Permanent +20 Max Health', baseCost: 400, costScale: 1.4, maxLevel: 5, stat: 'health', value: 20 },
  { id: 'perm_regen', name: 'Nano-Repair', description: 'Permanent +1 HP Regen', baseCost: 1000, costScale: 2.0, maxLevel: 3, stat: 'regen', value: 1 },
  { id: 'perm_amount', name: 'Multi-Threader', description: 'Permanent +1 Projectile', baseCost: 5000, coreCost: 5, costScale: 5.0, maxLevel: 1, stat: 'amount', value: 1 },
  { id: 'perm_revive', name: 'Emergency Reboot', description: 'Revive once per run with 50% HP', baseCost: 10000, coreCost: 10, costScale: 1.0, maxLevel: 1, stat: 'revive', value: 1 },
  { id: 'perm_magnet_range', name: 'Signal Range', description: 'Permanent +20% Magnet Range', baseCost: 500, costScale: 1.5, maxLevel: 5, stat: 'magnet_range', value: 0.2 },
  { id: 'perm_dash_cooldown', name: 'Dash Capacitor', description: 'Permanent -10% Dash Cooldown', baseCost: 800, costScale: 1.6, maxLevel: 5, stat: 'dash_cooldown', value: -0.1 },
  { id: 'perm_dash_speed', name: 'Vector Thrusters', description: 'Permanent +8% Dash Speed', baseCost: 900, costScale: 1.7, maxLevel: 5, stat: 'dash_speed', value: 0.08 },
  { id: 'perm_dash_duration', name: 'Overburn Core', description: 'Permanent +30ms Dash Duration', baseCost: 1000, costScale: 1.7, maxLevel: 5, stat: 'dash_duration', value: 30 },
  { id: 'perm_dash_impact', name: 'Impact Kernel', description: 'Permanent +15% Dash Impact Damage', baseCost: 1200, coreCost: 1, costScale: 1.8, maxLevel: 5, stat: 'dash_impact', value: 0.15 },
  { id: 'perm_dash_guard', name: 'Phase Weave', description: 'Permanent -12% Damage While Dashing', baseCost: 1400, coreCost: 1, costScale: 1.9, maxLevel: 4, stat: 'dash_guard', value: 0.12 },
  { id: 'perm_dash_repair', name: 'Recovery Injector', description: 'Restore +3 HP after each dash', baseCost: 1100, costScale: 1.8, maxLevel: 5, stat: 'dash_repair', value: 3 },
  { id: 'perm_dash_charge', name: 'Capacitor Bank', description: 'Permanent +1 Max Dash Charge', baseCost: 4500, coreCost: 2, costScale: 2.8, maxLevel: 2, stat: 'dash_charge', value: 1 },
  { id: 'perm_dash_recharge', name: 'Superconductor', description: 'Permanent -10% Dash Recharge Time', baseCost: 1600, coreCost: 1, costScale: 1.8, maxLevel: 5, stat: 'dash_recharge', value: 0.1 },
  { id: 'perm_dash_ghost', name: 'Ghost Frame', description: 'Gain +80ms invulnerability after dash end', baseCost: 2200, coreCost: 2, costScale: 2.0, maxLevel: 4, stat: 'dash_ghost', value: 80 },
  { id: 'perm_dash_momentum', name: 'Slipstream Drive', description: 'After dashing, gain +6% move speed for 1.5s', baseCost: 1300, costScale: 1.8, maxLevel: 5, stat: 'dash_momentum', value: 0.06 },
  { id: 'perm_starting_weapon', name: 'Weapon Cache', description: 'Start with an extra random weapon', baseCost: 15000, coreCost: 25, costScale: 1.0, maxLevel: 1, stat: 'extra_weapon', value: 1 },
  { id: 'perm_boss_damage', name: 'Titan Slayer', description: 'Permanent +20% Damage to Bosses', baseCost: 2000, coreCost: 2, costScale: 1.8, maxLevel: 5, stat: 'boss_damage', value: 0.2 },
  { id: 'perm_overdrive_ext', name: 'Overdrive Extension', name_s: 'Class-S', description: 'Overdrive duration +2 seconds', baseCost: 5000, coreCost: 5, costScale: 2.0, maxLevel: 5, stat: 'overdrive_duration', value: 2000 },
  { id: 'perm_reroll', name: 'Probability Matrix', description: 'Reroll upgrade choices once per run per level.', baseCost: 2000, coreCost: 1, costScale: 2.5, maxLevel: 3, stat: 'reroll', value: 1 },
  { id: 'perm_banish', name: 'Override Protocol', description: 'Banish an upgrade from the pool once per run per level.', baseCost: 3000, coreCost: 2, costScale: 3.0, maxLevel: 3, stat: 'banish', value: 1 },
  { id: 'perm_skip', name: 'System Bypass', description: 'Skip upgrade choice for a small XP bonus once per run per level.', baseCost: 1000, coreCost: 1, costScale: 2.0, maxLevel: 3, stat: 'skip', value: 1 },
];

export const OPERATOR_DEFINITIONS = [
  {
    id: 'phantom',
    name: 'Phantom',
    description: 'Standard neural operative. Balanced combat profile with plasma-based weaponry.',
    cost: 0,
    startingWeaponId: 'plasma_gun',
    statBonuses: {},
    baseHealth: 100,
    baseSpeed: 3.2,
    color: '#00ffff',
    colorSecondary: '#0d5e5e',
    colorDark: '#0a3d3d',
    colorGlow: 'rgba(0, 255, 255, 0.25)',
    colorVisor: '#00ffff',
    colorLimbs: '#00b8b8',
    colorBoots: '#006666',
  },
  {
    id: 'wraith',
    name: 'Wraith',
    description: 'Ghost protocol assassin. Extreme agility with crystalline shard projectors.',
    cost: 2000,
    startingWeaponId: 'neon_shards',
    statBonuses: { speed: 0.2, cooldown: -0.1 },
    baseHealth: 80,
    baseSpeed: 4.0,
    color: '#c084fc',
    colorSecondary: '#5b21b6',
    colorDark: '#3b0764',
    colorGlow: 'rgba(192, 132, 252, 0.25)',
    colorVisor: '#e879f9',
    colorLimbs: '#9333ea',
    colorBoots: '#581c87',
  },
  {
    id: 'titan',
    name: 'Titan',
    description: 'Heavy assault frame. Maximum armor with void-powered area denial systems.',
    cost: 5000,
    startingWeaponId: 'void_aura',
    statBonuses: { might: 0.3, area: 0.2, regen: 2 },
    baseHealth: 200,
    baseSpeed: 3.0,
    color: '#f97316',
    colorSecondary: '#9a3412',
    colorDark: '#431407',
    colorGlow: 'rgba(249, 115, 22, 0.25)',
    colorVisor: '#fb923c',
    colorLimbs: '#ea580c',
    colorBoots: '#7c2d12',
  },
  {
    id: 'spectre',
    name: 'Spectre',
    description: 'Recon specialist with drone swarm. Enhanced magnetic field and fortune matrix.',
    cost: 8000,
    startingWeaponId: 'orbit_drones',
    statBonuses: { area: 0.3, luck: 0.2, magnet_range: 0.3 },
    baseHealth: 90,
    baseSpeed: 3.4,
    color: '#4ade80',
    colorSecondary: '#166534',
    colorDark: '#052e16',
    colorGlow: 'rgba(74, 222, 128, 0.25)',
    colorVisor: '#86efac',
    colorLimbs: '#22c55e',
    colorBoots: '#14532d',
  },
  {
    id: 'reaper',
    name: 'Reaper',
    description: 'Executioner protocol. Devastating scythe with neural amplified critical strikes.',
    cost: 15000,
    startingWeaponId: 'data_scythe',
    statBonuses: { might: 0.3, boss_damage: 0.2, luck: 0.15 },
    baseHealth: 95,
    baseSpeed: 3.0,
    color: '#ef4444',
    colorSecondary: '#991b1b',
    colorDark: '#450a0a',
    colorGlow: 'rgba(239, 68, 68, 0.25)',
    colorVisor: '#fca5a5',
    colorLimbs: '#dc2626',
    colorBoots: '#7f1d1d',
  },
  {
    id: 'nexus',
    name: 'Nexus',
    description: 'Ascended entity. All neural pathways unlocked. The pinnacle of combat evolution.',
    cost: 30000,
    startingWeaponId: 'neural_pulse',
    statBonuses: { might: 0.15, area: 0.15, speed: 0.1, cooldown: -0.1, growth: 0.2, luck: 0.15 },
    baseHealth: 120,
    baseSpeed: 3.5,
    color: '#fbbf24',
    colorSecondary: '#92400e',
    colorDark: '#451a03',
    colorGlow: 'rgba(251, 191, 36, 0.25)',
    colorVisor: '#fde68a',
    colorLimbs: '#f59e0b',
    colorBoots: '#78350f',
  },
];
